### ISSUE TITLE
chore: opensourcing checklist

### ISSUE THREAD

**Issue by andela-anandaa** [andela/andela.github.io#6]
For this project to be fully "open-sourcey", I'd recommend the following checklist (feel free to add more):

- [ ] Proper README about the project + "how to contribute"
- [ ] CI well set up for tests (no worries about CD)
- [ ] Create some GH templates: `.github/PULL_REQUEST.md`, `.github/ISSUE_TEMPLATE.md`
- [ ] Decide on the release version (I think this can be a prelease) and we can release final 1.0.0 when most of the essentials are in place; then we adopt SemVer from there henceforth

**Comment by NdagiStanley** [comment]
Right on!
